# this is the main deployment file
# change everythings in this deployment file according to your needs
# nexus will be running on port 8081 and nginx will be running on port 8082 with https
# nexus data will be stored inside /nexus-data/ directory
# nginx is using configuration file in /etc/nginx/conf.d/nexus_nginx.conf and ssl certs in /etc/ssl/certs/

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  containers:
    - name: nexus
      image: sonatype/nexus3:latest
      ports:
        - containerPort: 8081
          hostPort: 8081
      volumeMounts:
        - mountPath: /nexus-data/:Z,U
          name: nexus_data
      resources: {}
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 8082
          hostPort: 8082
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/nexus_nginx.conf:Z
          name: nexus_nginx_configuration
        - mountPath: /etc/ssl/certs/:Z
          name: nexus_nginx_ssl_certificates
      resources: {}
  volumes:
    - name: nexus_data
      hostPath:
        path: ./nexus/data
        type: Directory
    - name: nexus_nginx_configuration
      hostPath:
        path: ./nginx/nexus_nginx.conf
        type: File
    - name: nexus_nginx_ssl_certificates
      hostPath:
        path: ./nginx/certs/
        type: Directory